#
# Copyright (c) 2019 Carnegie Mellon University,
# Copyright (c) 2019 Triad National Security, LLC, as operator of
#     Los Alamos National Laboratory.
#
# All rights reserved.
#
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file. See the AUTHORS file for names of contributors.
#

language: cpp
sudo: required
dist: xenial

compiler:
  - gcc

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - automake
      - libboost-dev
      - libibverbs-dev
      - librdmacm-dev
      - libmpich-dev
      - libpapi-dev
      - libnuma-dev
      - mpich
      - g++-4.6
      - g++-4.8
      - g++-5
      - g++-6
      - g++-7
      - g++-8

env:
  global:
    - GIT_SSL_NO_VERIFY=true
  matrix:
    - GCC=4.6
    - GCC=4.8
    - GCC=5
    - GCC=6
    - GCC=7
    - GCC=8

install:
  - export CXX="g++-${GCC}"
  - export CC="gcc-${GCC}"

before_script:
  - ${CXX} --version
  - ${CC} --version
  - automake --version
  - cmake --version
  - git --version

script:
  - date
  - mkdir -p /tmp/deltafs
  - git lfs pull --include "cache.0/ch-placement*"
  - cd cache
  - ln -fs ../cache.0/ch-placement* .
  - ls -l
  - cd ..
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp/deltafs -DMERCURY_OPA=TRUE -DUMBRELLA_BUILD_TESTS=OFF -DUMBRELLA_SKIP_TESTS=ON .
  - make
  - date

git:
  lfs_skip_smudge: true
  submodules: false

branches:
  only:
    - master
