language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

os:
  - linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:git-core/ppa'
      - sourceline: 'ppa:george-edison55/cmake-3.x'
      - ubuntu-toolchain-r-test
    packages:
      - automake
      - libboost-dev
      - libibverbs-dev
      - librdmacm-dev
      - libmpich-dev
      - libpapi-dev
      - libnuma-dev
      - mpich
      - git
      - cmake-data
      - cmake
      - g++-4.6
      - g++-4.8
      - g++-5
      - g++-6
      - g++-7
      - g++-8

env:
  global:
    - GIT_SSL_NO_VERIFY=true
  matrix:
    - GCC=4.6
    - GCC=4.8
    - GCC=5
    - GCC=6
    - GCC=7
    - GCC=8

install:
  - export CXX="g++-${GCC}"
  - export CC="gcc-${GCC}"

before_script:
  - ${CXX} --version
  - ${CC} --version
  - automake --version
  - cmake --version
  - git --version

script:
  - date
  - mkdir -p /tmp/deltafs
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp/deltafs -DMERCURY_OPA=TRUE -DUMBRELLA_BUILD_TESTS=OFF -DUMBRELLA_SKIP_TESTS=ON .
  - make
  - date

git:
  lfs_skip_smudge: true
  submodules: false

branches:
  only:
    - master
