language: cpp
compiler:
- gcc
os:
- linux
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
script:
- mkdir -p /tmp/deltafs
- cmake -DCMAKE_INSTALL_PREFIX=/tmp/deltafs .
- make
git:
  submodules: false
branches:
  only:
    - master
